# Generated by Django 5.2 on 2025-04-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ClientSocialnetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialnetworlk_client', to='clients.client')),
                ('socialnetwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_client_socialnetwork', to='socialnetworks.socialnetwork')),
            ],
            options={
                'verbose_name': 'Rede Social do Cliente',
                'verbose_name_plural': 'Redes Sociais dos Clientes',
                'ordering': ['id'],
            },
        ),
    ]
