# Generated by Django 5.1.7 on 2025-04-28 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socialnetworks", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Sobrenome"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Endereco")),
                (
                    "cell_phone",
                    models.CharField(max_length=20, verbose_name="Telefone celular"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        verbose_name="Genero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ClientSocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_network_client",
                        to="clients.client",
                    ),
                ),
                (
                    "socialNetwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_social_network",
                        to="socialnetworks.socialnetwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Redes Social",
                "verbose_name_plural": "Itens de Rede Social",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="client_socialNetwork",
            field=models.ManyToManyField(
                blank=True,
                through="clients.ClientSocialNetwork",
                to="socialnetworks.socialnetwork",
            ),
        ),
    ]
